// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: sdn/sdn.proto

package sdn

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceType int32

const (
	DeviceType_HOST       DeviceType = 0
	DeviceType_INC_SWITCH DeviceType = 1
	DeviceType_NET        DeviceType = 2
	DeviceType_EXTERNAL   DeviceType = 3
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "HOST",
		1: "INC_SWITCH",
		2: "NET",
		3: "EXTERNAL",
	}
	DeviceType_value = map[string]int32{
		"HOST":       0,
		"INC_SWITCH": 1,
		"NET":        2,
		"EXTERNAL":   3,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_sdn_sdn_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_sdn_sdn_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_sdn_sdn_proto_rawDescGZIP(), []int{0}
}

type Link struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerName string `protobuf:"bytes,1,opt,name=peerName,proto3" json:"peerName,omitempty"`
}

func (x *Link) Reset() {
	*x = Link{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdn_sdn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_sdn_sdn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_sdn_sdn_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetPeerName() string {
	if x != nil {
		return x.PeerName
	}
	return ""
}

type Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DeviceType DeviceType `protobuf:"varint,2,opt,name=deviceType,proto3,enum=sdn.DeviceType" json:"deviceType,omitempty"`
	Links      []*Link    `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
}

func (x *Device) Reset() {
	*x = Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdn_sdn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_sdn_sdn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_sdn_sdn_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_HOST
}

func (x *Device) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

type TopologyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Graph []*Device `protobuf:"bytes,1,rep,name=graph,proto3" json:"graph,omitempty"`
}

func (x *TopologyResponse) Reset() {
	*x = TopologyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdn_sdn_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyResponse) ProtoMessage() {}

func (x *TopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdn_sdn_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyResponse.ProtoReflect.Descriptor instead.
func (*TopologyResponse) Descriptor() ([]byte, []int) {
	return file_sdn_sdn_proto_rawDescGZIP(), []int{2}
}

func (x *TopologyResponse) GetGraph() []*Device {
	if x != nil {
		return x.Graph
	}
	return nil
}

type SwitchNames struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *SwitchNames) Reset() {
	*x = SwitchNames{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdn_sdn_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwitchNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchNames) ProtoMessage() {}

func (x *SwitchNames) ProtoReflect() protoreflect.Message {
	mi := &file_sdn_sdn_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchNames.ProtoReflect.Descriptor instead.
func (*SwitchNames) Descriptor() ([]byte, []int) {
	return file_sdn_sdn_proto_rawDescGZIP(), []int{3}
}

func (x *SwitchNames) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type SwitchDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arch             string `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	InstalledProgram string `protobuf:"bytes,3,opt,name=installedProgram,proto3" json:"installedProgram,omitempty"`
}

func (x *SwitchDetails) Reset() {
	*x = SwitchDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdn_sdn_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwitchDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchDetails) ProtoMessage() {}

func (x *SwitchDetails) ProtoReflect() protoreflect.Message {
	mi := &file_sdn_sdn_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchDetails.ProtoReflect.Descriptor instead.
func (*SwitchDetails) Descriptor() ([]byte, []int) {
	return file_sdn_sdn_proto_rawDescGZIP(), []int{4}
}

func (x *SwitchDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SwitchDetails) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SwitchDetails) GetInstalledProgram() string {
	if x != nil {
		return x.InstalledProgram
	}
	return ""
}

type SwitchDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Details map[string]*SwitchDetails `protobuf:"bytes,1,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SwitchDetailsResponse) Reset() {
	*x = SwitchDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdn_sdn_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwitchDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchDetailsResponse) ProtoMessage() {}

func (x *SwitchDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdn_sdn_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchDetailsResponse.ProtoReflect.Descriptor instead.
func (*SwitchDetailsResponse) Descriptor() ([]byte, []int) {
	return file_sdn_sdn_proto_rawDescGZIP(), []int{5}
}

func (x *SwitchDetailsResponse) GetDetails() map[string]*SwitchDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type ProgramDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProgramName string `protobuf:"bytes,1,opt,name=programName,proto3" json:"programName,omitempty"`
}

func (x *ProgramDetailsRequest) Reset() {
	*x = ProgramDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdn_sdn_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProgramDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramDetailsRequest) ProtoMessage() {}

func (x *ProgramDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdn_sdn_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramDetailsRequest.ProtoReflect.Descriptor instead.
func (*ProgramDetailsRequest) Descriptor() ([]byte, []int) {
	return file_sdn_sdn_proto_rawDescGZIP(), []int{6}
}

func (x *ProgramDetailsRequest) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

type ProgramDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImplementedInterfaces []string `protobuf:"bytes,2,rep,name=implementedInterfaces,proto3" json:"implementedInterfaces,omitempty"`
}

func (x *ProgramDetailsResponse) Reset() {
	*x = ProgramDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdn_sdn_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProgramDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramDetailsResponse) ProtoMessage() {}

func (x *ProgramDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdn_sdn_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramDetailsResponse.ProtoReflect.Descriptor instead.
func (*ProgramDetailsResponse) Descriptor() ([]byte, []int) {
	return file_sdn_sdn_proto_rawDescGZIP(), []int{7}
}

func (x *ProgramDetailsResponse) GetImplementedInterfaces() []string {
	if x != nil {
		return x.ImplementedInterfaces
	}
	return nil
}

var File_sdn_sdn_proto protoreflect.FileDescriptor

var file_sdn_sdn_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x64, 0x6e, 0x2f, 0x73, 0x64, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x73, 0x64, 0x6e, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x22, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x65, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x6e, 0x0a, 0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x73, 0x64, 0x6e, 0x2e, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x73, 0x64, 0x6e, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x05,
	0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x35, 0x0a, 0x10, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x64, 0x6e, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x05, 0x67, 0x72, 0x61, 0x70, 0x68, 0x22, 0x23, 0x0a, 0x0b,
	0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x22, 0x63, 0x0a, 0x0d, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x63, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x63, 0x68, 0x12, 0x2a, 0x0a, 0x10, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x22, 0xaa, 0x01, 0x0a, 0x15, 0x53, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x41, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x73, 0x64, 0x6e, 0x2e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x1a, 0x4e, 0x0a, 0x0c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x64, 0x6e, 0x2e, 0x53, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x39, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4e,
	0x0a, 0x16, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x15, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x15, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2a, 0x3d,
	0x0a, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04,
	0x48, 0x4f, 0x53, 0x54, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x4e, 0x43, 0x5f, 0x53, 0x57,
	0x49, 0x54, 0x43, 0x48, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x54, 0x10, 0x02, 0x12,
	0x0c, 0x0a, 0x08, 0x45, 0x58, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x03, 0x32, 0xe1, 0x01,
	0x0a, 0x0b, 0x53, 0x64, 0x6e, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x12, 0x3e, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x73, 0x64, 0x6e, 0x2e, 0x54, 0x6f, 0x70, 0x6f, 0x6c,
	0x6f, 0x67, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x10, 0x2e, 0x73, 0x64, 0x6e, 0x2e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x1a, 0x1a, 0x2e, 0x73, 0x64, 0x6e, 0x2e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1a, 0x2e, 0x73, 0x64, 0x6e, 0x2e, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x64, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x46, 0x6c, 0x30, 0x6b, 0x33, 0x6e, 0x2f, 0x6b, 0x38, 0x73, 0x2d, 0x69, 0x6e, 0x63, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x64, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sdn_sdn_proto_rawDescOnce sync.Once
	file_sdn_sdn_proto_rawDescData = file_sdn_sdn_proto_rawDesc
)

func file_sdn_sdn_proto_rawDescGZIP() []byte {
	file_sdn_sdn_proto_rawDescOnce.Do(func() {
		file_sdn_sdn_proto_rawDescData = protoimpl.X.CompressGZIP(file_sdn_sdn_proto_rawDescData)
	})
	return file_sdn_sdn_proto_rawDescData
}

var file_sdn_sdn_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdn_sdn_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sdn_sdn_proto_goTypes = []interface{}{
	(DeviceType)(0),                // 0: sdn.DeviceType
	(*Link)(nil),                   // 1: sdn.Link
	(*Device)(nil),                 // 2: sdn.Device
	(*TopologyResponse)(nil),       // 3: sdn.TopologyResponse
	(*SwitchNames)(nil),            // 4: sdn.SwitchNames
	(*SwitchDetails)(nil),          // 5: sdn.SwitchDetails
	(*SwitchDetailsResponse)(nil),  // 6: sdn.SwitchDetailsResponse
	(*ProgramDetailsRequest)(nil),  // 7: sdn.ProgramDetailsRequest
	(*ProgramDetailsResponse)(nil), // 8: sdn.ProgramDetailsResponse
	nil,                            // 9: sdn.SwitchDetailsResponse.DetailsEntry
	(*empty.Empty)(nil),            // 10: google.protobuf.Empty
}
var file_sdn_sdn_proto_depIdxs = []int32{
	0,  // 0: sdn.Device.deviceType:type_name -> sdn.DeviceType
	1,  // 1: sdn.Device.links:type_name -> sdn.Link
	2,  // 2: sdn.TopologyResponse.graph:type_name -> sdn.Device
	9,  // 3: sdn.SwitchDetailsResponse.details:type_name -> sdn.SwitchDetailsResponse.DetailsEntry
	5,  // 4: sdn.SwitchDetailsResponse.DetailsEntry.value:type_name -> sdn.SwitchDetails
	10, // 5: sdn.SdnFrontend.GetTopology:input_type -> google.protobuf.Empty
	4,  // 6: sdn.SdnFrontend.GetSwitchDetails:input_type -> sdn.SwitchNames
	7,  // 7: sdn.SdnFrontend.GetProgramDetails:input_type -> sdn.ProgramDetailsRequest
	3,  // 8: sdn.SdnFrontend.GetTopology:output_type -> sdn.TopologyResponse
	6,  // 9: sdn.SdnFrontend.GetSwitchDetails:output_type -> sdn.SwitchDetailsResponse
	8,  // 10: sdn.SdnFrontend.GetProgramDetails:output_type -> sdn.ProgramDetailsResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_sdn_sdn_proto_init() }
func file_sdn_sdn_proto_init() {
	if File_sdn_sdn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sdn_sdn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Link); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdn_sdn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdn_sdn_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopologyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdn_sdn_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwitchNames); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdn_sdn_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwitchDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdn_sdn_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwitchDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdn_sdn_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProgramDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdn_sdn_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProgramDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sdn_sdn_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdn_sdn_proto_goTypes,
		DependencyIndexes: file_sdn_sdn_proto_depIdxs,
		EnumInfos:         file_sdn_sdn_proto_enumTypes,
		MessageInfos:      file_sdn_sdn_proto_msgTypes,
	}.Build()
	File_sdn_sdn_proto = out.File
	file_sdn_sdn_proto_rawDesc = nil
	file_sdn_sdn_proto_goTypes = nil
	file_sdn_sdn_proto_depIdxs = nil
}
