apiVersion: inc.kntp.com/v1alpha1
kind: Topology
metadata:
  labels:
    app.kubernetes.io/name: topology
    app.kubernetes.io/instance: topology-sample
    app.kubernetes.io/part-of: sdn-shim
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sdn-shim
  name: topology-sample
spec:
  # TODO(user): Add fields here
