## Append samples you want in your CSV to this file as resources ##
resources:
- inc_v1alpha1_topology.yaml
- inc_v1alpha1_incswitch.yaml
- inc_v1alpha1_sdnshim.yaml
- inc_v1alpha1_p4program.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
