# permissions for end users to view incswitches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: incswitch-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: inc
    app.kubernetes.io/part-of: inc
    app.kubernetes.io/managed-by: kustomize
  name: incswitch-viewer-role
rules:
- apiGroups:
  - inc.kntp.com
  resources:
  - incswitches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - incswitches/status
  verbs:
  - get
