---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - inc.kntp.com
  resources:
  - incswitches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - incswitches/finalizers
  verbs:
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - incswitches/status
  verbs:
  - get
  - patch
  - update
