apiVersion: inc.example.com/v1alpha1
kind: p4program # resource for programs for devices with p4runtime
metadata:
  name: telemetry
spec:
  artifacts:
    - arch: bmv2
      p4info: infoPath # need some way to access this, controller must be able to download it, maybe s3 bucket or smth, but make it generic
      p4pipeline: pipelinePath # url or raw whatever
    - arch: anotherArch # eg tofino
      p4Info: infoPath
      p4pipeline: pipelinePath
