# permissions for end users to view internalinnetworktelemetryendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: internalinnetworktelemetryendpoints-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: inc-operator
    app.kubernetes.io/part-of: inc-operator
    app.kubernetes.io/managed-by: kustomize
  name: internalinnetworktelemetryendpoints-viewer-role
rules:
- apiGroups:
  - inc.kntp.com
  resources:
  - internalinnetworktelemetryendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - internalinnetworktelemetryendpoints/status
  verbs:
  - get
