---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - inc.kntp.com
  resources:
  - collectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - collectors/finalizers
  verbs:
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - collectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - daemonsets/status
  verbs:
  - get
- apiGroups:
  - inc.kntp.com
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - externalinnetworktelemetrydeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - externalinnetworktelemetrydeployments/finalizers
  verbs:
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - externalinnetworktelemetrydeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - externalinnetworktelemetryendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - externalinnetworktelemetryendpoints/finalizers
  verbs:
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - externalinnetworktelemetryendpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - incswitches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - incswitches/status
  verbs:
  - get
- apiGroups:
  - inc.kntp.com
  resources:
  - internalinnetworktelemetrydeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - internalinnetworktelemetrydeployments/finalizers
  verbs:
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - internalinnetworktelemetrydeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - internalinnetworktelemetryendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - internalinnetworktelemetryendpoints/finalizers
  verbs:
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - internalinnetworktelemetryendpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - nodes/status
  verbs:
  - get
- apiGroups:
  - inc.kntp.com
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - replicasets/finalizers
  verbs:
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - replicasets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - sdnshims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - sdnshims/finalizers
  verbs:
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - sdnshims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - services/status
  verbs:
  - get
- apiGroups:
  - inc.kntp.com
  resources:
  - telemetrydeviceresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - telemetrydeviceresources/finalizers
  verbs:
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - telemetrydeviceresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - topologies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inc.kntp.com
  resources:
  - topologies/finalizers
  verbs:
  - update
- apiGroups:
  - inc.kntp.com
  resources:
  - topologies/status
  verbs:
  - get
  - patch
  - update
