apiVersion: inc.example.com/v1alpha1
kind: ExternalTelemetryDeployment
metadata:
  name: webAppTelemetry
spec:
  selector:
    label: myWebApp
  collector:
    selector:
      label: myCollector
    config: ...
  monitorFromInternetToPods: true
  monitorFromPodsToInternet: true
# this variant takes running deployment as-is and adds telemetry wherever possible
# some pods may end up without telemetry
# no scheduling necessary, just set entries of selected devices and setup collector
