apiVersion: inc.kntp.com/v1alpha1
kind: Collector
metadata:
  name: collector
spec:
  podSpec:
    nodeName: tree-worker1
    containers:
      - name: nodeapp
        image: flok3n/int-collector:1.0.0
        ports:
          - containerPort: 6000
