apiVersion: inc.kntp.com/v1alpha1
kind: Collector
metadata:
  name: collector
spec:
  podSpec:
    nodeName: tree-worker4
    containers:
      - name: nodeapp
        image: flok3n/int-collector:1.0.2
        command:
          ["python3", "/app/server.py", "-i", "6000", "-o", "/logs/reports.csv"]
        ports:
          - containerPort: 6000
        volumeMounts:
          - name: logs-dir
            mountPath: /logs
    volumes:
      - name: logs-dir
        hostPath:
          path: /logs
