apiVersion: inc.kntp.com/v1alpha1
kind: ExternalInNetworkTelemetryDeployment
metadata:
  name: eintdepl
spec:
  requiredProgram: telemetry
  ingressInfo:
    type: NodePort
    serviceName: receiversvc
    serviceNamespace: default
    nodeNames:
      - tree-worker3
  monitoringPolicy: all
  requireAtLeastIntDevices: "3"
  deploymentTemplate:
    replicas: 1
    selector:
      matchLabels:
        app: example
    template:
      metadata:
        labels:
          app: example
      spec:
        terminationGracePeriodSeconds: 0
        containers:
          - name: receiver
            image: flok3n/receiver_tcp:1.0.0
            command: ["python3", "/receiver_tcp.py", "8959"]
            ports:
              - containerPort: 8959
---
apiVersion: v1
kind: Service
metadata:
  name: receiversvc
spec:
  selector:
    app: example
  type: NodePort
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8959
      nodePort: 30008
