apiVersion: inc.kntp.com/v1alpha1
kind: InternalInNetworkTelemetryDeployment
metadata:
  name: intdepl
spec:
  collectorRef:
    name: collector
  deployments:
    - name: receiver
      template:
        replicas: 1
        selector:
          matchLabels:
            app: rcv
        template:
          metadata:
            labels:
              app: rcv
          spec:
            terminationGracePeriodSeconds: 0
            containers:
              - name: receiver
                image: flok3n/receiver_tcp:1.0.3
                command: ["python3", "/receiver_tcp.py", "8959"]
                ports:
                  - containerPort: 8959
    - name: sender
      template:
        replicas: 1
        selector:
          matchLabels:
            app: snd
        template:
          metadata:
            labels:
              app: snd
          spec:
            terminationGracePeriodSeconds: 0
            containers:
              - name: sender
                image: flok3n/sender_tcp:1.0.3
                imagePullPolicy: Always
                command:
                  [
                    "python3",
                    "/sender_tcp.py",
                    "tcp-recv.default.svc.cluster.local",
                    "8959",
                  ]
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-recv
spec:
  selector:
    app: rcv
  ports:
    - protocol: TCP
      port: 8959
      targetPort: 8959
